version: '3.8'
services:
  database:
    image: "mongo:${TAG}"
    container_name: mongo-server
    environment:
     MONGO_INITDB_DATABASE: "${DB_NAME}"
     MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
     MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    volumes:      
      # - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db  
  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
volumes:
  mongodb_data_container: