name: Test Hessian CMS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Upload repository
      uses: actions/upload-artifact@v3
      with:
        name: repo-plain
        path: ./
  setup:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: Show node --version
      run: node --version
  install:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: Install dependencies
      run: npx yarn install
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: Walk tests
      run: npx yarn test