name: Test Hessian CMS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: node --version
      run: node --version
    - name: Install dependencies
      run: npx yarn install
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: node --version
      run: node --version
    - name: Install dependencies
      run: npx yarn install
    - name: Lint project
      run: npx yarn run lint
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: node --version
      run: node --version
    - name: Install dependencies
      run: npx yarn install
    - name: Walk tests
      run: npx yarn test
  finalize:
    needs:
    - install
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: node --version
      run: node --version