name: Test Hessian CMS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with: 
        node-version: 16.x
    - name: Run tests
      run: npx yarn install
    - name: Walk tests
      run: npx yarn test
      
    
    
